### ISSUE TITLE
Crashes when item has no aspects

### ISSUE THREAD

**Issue by fin600** [blay09/TCInventoryScanning#7]
Scanned a Tinker's Construct thing without any aspects and it crashed promptly. Needs some sort of error handling where it puts out 'nothing can be learned from this'. http://pastebin.com/D3gCnBmG

**Comment by Sasikaa** [comment]
YES! My crash is... The ferrous ore Thermal Found. when scan the Diamond chest, crash. My crash report same...
java.lang.StackOverflowError: Unexpected error
	at thaumcraft.api.aspects.AspectList.getAspects(AspectList.java:65)
	at thaumcraft.api.aspects.AspectList.copy(AspectList.java:35)
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromCrucibleRecipes(ThaumcraftCraftingManager.java:567)
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromRecipes(ThaumcraftCraftingManager.java:891)
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:551)
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:525)

**Comment by blay09** [comment]
I think this is some kind of mod-interaction issue. I doesn't happen to me when scanning Tinkers tools. I also can't find anything wrong with the code. From looking at Thaumcraft code, it looks like there's a crucible recipe that uses itself as a catalyst, and it really doesn't like that at all... did you try scanning it normally without the inventory scan?
